# Header
navname: 主页

# navigatior items
nav:
  # 最高: /top
  # 文章: /archives
  # CV: /CV
  # CV: /CV-English
  # CV-English: /CV-English
  # Publications: /Publications
  博文: /top
  类别: /category
  标签: /tag
  关于: /about
  
  
# favicon
# 页面logo
# favicon: /favicon.ico
favicon: /rocket_favicon.ico

# Profile
nickname: Myoontyee Chen

### this variable is MarkDown form.
description: 
    <h1>中国科学院 医学成像系统 硕士在读</h1>
    <h2>多传感器 / 探测器融合系统</h2>   
   <br>
   <p><h2>研究领域</h2></p>
    <hr />
    <p><h3>医学成像系统：Proton CT / Carbon CT ·<a href="tags/Geant4/"> <u>Geant4</u></a> · <a href="tags/CERN-ROOT/"><u>ROOT</u></a></h3></p>
    <p><h3>Robotic：<a href="categories/数理与算法/"> <u>数理与算法</u></a> · <a href="categories/Neural-Network/"><u>神经网络</u></a> · <a href="categories/函数/"><u>函数</u></a></h3></p>

avatar: /image/Meow.jpg

# main menu navigation
## links key words should not be changed.
## Complete url after key words.
## Unused key can be commented out.
links:
  Blog: /archives
  # Category:
  # Tags: 
  # Link:
  # Resume:
  # Publish:
  # Trophy:
  # Gallery:
  # RSS:
  # AliPay:
  # ZhiHu: https://www.zhihu.com/people/sirice
  # LinkedIn:
  # FaceBook:
  # Twitter:
  # Skype:
  # CodeSandBox:
  # CodePen:
  # Sketch:
  # Gitlab:
  # Dribbble:
  # Instagram:
  # Reddit:
  # YouTube:
  # QQ:
  # Weibo:
  # WeChat:
  Github: https://github.com/Myoontyee
  jianshu: https://www.jianshu.com/u/0044b2811860
  csdn: https://blog.csdn.net/myoonyee_chen_csdn


# how links show: you have 2 choice--text or icon.
links_text_enable: false
links_icon_enable: true

# Post page
## Post_meta
post_meta_enable: true

post_author_enable: true
post_date_enable: true
post_category_enable: true
## Post copyright
post_copyright_enable: true

post_copyright_author_enable: false
post_copyright_permalink_enable: false
post_copyright_license_enable: false
post_copyright_license_text: Copyright (c) 2019 <a href="http://creativecommons.org/licenses/by-nc/4.0/">CC-BY-NC-4.0</a> LICENSE
post_copyright_slogan_enable: false
post_copyright_slogan_text: <strong>寻求读博机会</strong>?
## toc
post_toc_enable: true

# Page
page_title_enable: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: MMMM D, YYYY
time_format: H:mm:ss

# stylesheets loaded in the <head>
stylesheets:
  - /css/style.css
  - ../fonts/iconfont2/iconfont.css
  - ../fonts/iconfont3/iconfont.css
  - ../fonts/iconfont4/iconfont.css
  - //cdn.bootcss.com/font-awesome/4.3.0/css/font-awesome.min.css # 访客量的旋转等待logo


searchImg: /image/search.png
# scripts loaded in the end of the body
scripts:
  - /js/script.js
  - /js/tocbot.min.js
  - /js/jquery.min.js # 搜索引擎用
    # tscanlin/tocbot: Build a table of contents from headings in an HTML document.
    # https://github.com/tscanlin/tocbot


# plugin functions
## Mathjax: Math Formula Support
## https://www.mathjax.org
mathjax:
  enable: true
  import: demand # global or demand
  ## global: all pages will load mathjax,this will degrade performance and some grammers may be parsed wrong.
  ## demand: Recommend option,if your post need fomula, you can declare 'mathjax: true' in Front-matter
  
katex:
  enable: true

# 评论区
gitalk:
  enable: true
  ClientID: 84b52a29ce9e713ad7d4 #Client ID,填入上一步获取的ID
  ClientSecret: 95578b09122163e717247e0b28e6c76fc3976dcf #Client Secret，填入上一步获取的ID
  repo: myoontyee.github.io #你要存放的项目名,如果博客部署在github可以放一起
  owner: Myoontyee #这个项目名的拥有者（GitHub账号或组织）
  adminUser: ['Myoontyee'] #管理员用户
  ID: location.pathname #页面ID
  labels: ['Gitalk'] #GitHub issues的标签
  perPage: 10 #每页多少个评论
  pagerDirection: last #排序方式是从旧到新（first），还是从新到旧（last）
  createIssueManually: true #是否自动创建isssue，自动创建需要当前登录的用户为adminuser
  distractionFreeMode: false #是否启用快捷键(cmd|ctrl + enter) 提交评论



# 文章字数和阅读时长
# Post wordcount display settings
# Dependencies: https://github.com/willin/hexo-wordcount
post_wordcount:
  item_text: true
  wordcount: true         # 单篇 字数统计
  min2read: true          # 单篇 阅读时长
  totalcount: false       # 网站 字数统计
post_wordcount_enable: true   # 字数统计
post_min2read_enable: true    # 阅读时长


# 访客数
# 站浏览数统计
visit_counter: 
  site_uv: true # 访客数量
  site_pv: true # 浏览次数


mermaid:
  version: 8.14.0 
  enable: true # 默认为 True
  # Available themes: default | dark | forest | neutral
  # theme: forest



